Traceback (most recent call last):
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/nbclient/client.py", line 627, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/nbclient/util.py", line 89, in ensure_async
    result = await obj
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/nbclient/client.py", line 651, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/home/wschoi/exit/envs/tutorial-environment/lib/python3.9/site-packages/nbclient/client.py", line 701, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 500 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['from IPython.display import Audio, display', 'from lasaft.pretrained import get_v2_large_709', '', 'model = get_v2_large_709()', "result = model.separate_tracks(mixture, ['vocals', 'drums', 'bass', 'other'], batch_size=4)"]
...
['for source in ["vocals", "drums", "bass", "other"]:', "    print('{} (v1)'.format(source))", '    display(Audio(url="{}/{}-{}.wav".format(v1_url, track, source)))', "    print('{} (v2)'.format(source))", '    display(Audio(result[source].T, rate=44100))']
-------------------

